{
 "title": "kube-dns",
 "tags": [ "clone-from-dev" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Rate", "query": "30s,1m,5m,15m" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(skydns_skydns_dns_request_count_total, job)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(skydns_skydns_dns_request_count_total{job=~\"$Job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container resource metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-system\", pod=~\"$Pod\", container!=\"\"}",
     "legendFormat": "{{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kube-system\", pod=~\"$Pod\", container!=\"\"}[$Rate])",
     "legendFormat": "{{ pod }} / {{ container }}"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{namespace=\"kube-system\", pod=~\"$Pod\", container!=\"\"}[$Rate])",
     "legendFormat": "CPU Throttled {{ container }}"
    }
   ]
  },
  {
   "title": "container_cpu_cfs_throttled_periods_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{namespace=\"kube-system\", pod=~\"$Pod\", container!=\"\"}[$Rate])",
     "legendFormat": "{{ pod }} / {{ container }}"
    }
   ]
  },
  {
   "title": "kube-dns Pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"kube-system\", pod=~\"$Pod\", condition=\"true\"})",
     "legendFormat": "Total pods"
    }
   ]
  },
  { "title": "dnsmasq - Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "dnsmasq processes",
   "type": "timeseries",
   "description": "Number of processes in `dnsmasq` container.\n\n`dnsmasq` has a hard coded limit of 20 child processes so if this reaches 22 it will severely affect latency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "container_processes{namespace=\"kube-system\", pod=~\"$Pod\", container=\"dnsmasq\"}",
     "legendFormat": "{{ pod }}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS Probe Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg by (le) (rate(kubedns_probe_kubedns_latency_ms_bucket{job=~\"$Job\", pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "{{ le }}"
    },
    {
     "expr": "avg by (le) (rate(kubedns_probe_dnsmasq_latency_ms_bucket{job=~\"$Job\", pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "P99 Probe latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubedns_probe_kubedns_latency_ms_bucket{job=\"$Job\",pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "P99 kubedns_probe_kubedns_latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubedns_probe_dnsmasq_latency_ms_bucket{job=\"$Job\",pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "P99 kubedns_probe_dnsmasq_latency"
    }
   ]
  },
  {
   "title": "dnsmasq: insertions and evictions rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(kubedns_dnsmasq_insertions{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])",
     "legendFormat": "Insertions / {{ pod }}"
    },
    {
     "expr": "rate(kubedns_dnsmasq_evictions{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])",
     "legendFormat": "Evictions / {{ pod }}"
    }
   ]
  },
  {
   "title": "dnsmasq: errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "rate(kubedns_probe_dnsmasq_errors{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])",
     "legendFormat": "Probe errors / {{ pod }}"
    },
    {
     "expr": "rate(kubedns_dnsmasq_errors{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])",
     "legendFormat": "DNSMasq errors / {{ pod }}"
    }
   ]
  },
  {
   "title": "dnsmasq: Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits{job=~\"$Job\", pod=~\"$Pod\"}[1m])) by (pod) / (sum(rate(kubedns_dnsmasq_misses{job=~\"$Job\", pod=~\"$Pod\"}[1m])) by (pod) + sum(rate(kubedns_dnsmasq_hits{job=~\"$Job\", pod=~\"$Pod\"}[1m])) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "dnsmasq: Hits and Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kubedns_dnsmasq_misses{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod) + sum(rate(kubedns_dnsmasq_hits{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod)",
     "legendFormat": "Total {{ pod }}"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_misses{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod)",
     "legendFormat": "Misses / {{ pod }}"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod)",
     "legendFormat": "Hits / {{ pod }}"
    }
   ]
  },
  { "title": "SkyDNS - Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "SkyDNS: Response Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg (irate(skydns_skydns_dns_request_duration_seconds_bucket{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "SkyDNS: Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(skydns_skydns_dns_request_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (rate(skydns_skydns_dns_request_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "SkyDNS: Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_error_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(skydns_skydns_dns_error_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod, cause)",
     "legendFormat": "{{ pod }} / {{ cause }}"
    }
   ]
  },
  {
   "title": "SkyDNS: Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(skydns_skydns_dns_request_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod) / sum(rate(skydns_skydns_dns_cachemiss_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "SkyDNS: Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_cachemiss_count_total{job=~\"$Job\", pod=~\"$Pod\"}[$Rate])) by (pod)",
     "legendFormat": "Cache misses {{ pod }}"
    }
   ]
  }
 ]
}