{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server with updated metrics for version 1.7.0+.  Based on the CoreDNS dashboard by buhay.",
 "tags": [ "clone-from-dev" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "PrometheusJob", "query": "node-local-dns-metrics,coredns" },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(up{job=\"$PrometheusJob\"}, pod)"
    }
   },
   { "name": "Rate", "query": "30s,1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache (size)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{job=\"$PrometheusJob\",pod=~\"$Pod\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (proto) or\nsum(rate(coredns_dns_requests_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (type) or \nsum(rate(coredns_dns_requests_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (zone) or\nsum(rate(coredns_dns_requests_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Requests (DO bit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_do_count_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) or\nsum(rate(coredns_dns_do_requests_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) or\nsum(rate(coredns_dns_requests_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"udp\"}[$Rate])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"udp\"}[$Rate])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"udp\"}[$Rate])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests (size,tcp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"tcp\"}[$Rate])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"tcp\"}[$Rate])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"tcp\"}[$Rate])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (rcode) or\nsum(rate(coredns_dns_responses_total{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "99% / {{ pod }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "90% / {{ pod }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Responses (duration) by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\"}[$Rate])) by (le, pod))",
     "legendFormat": "99% / {{ pod }}"
    }
   ]
  },
  {
   "title": "Responses (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"udp\"}[$Rate])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"udp\"}[$Rate])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"udp\"}[$Rate])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (size, tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"tcp\"}[$Rate])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"tcp\"}[$Rate])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\",proto=\"tcp\"}[$Rate])) by (le, proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  { "title": "Connection cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Connection cache hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(coredns_forward_conn_cache_hits_total{to!~\"8.8.4.4:53|8.8.8.8:53|169.254.169.254:53\", pod=~\"$Pod\"}[$Rate])",
     "legendFormat": "Hits {{ pod }}"
    },
    {
     "expr": "sum(rate(coredns_forward_conn_cache_hits_total{to!~\"8.8.4.4:53|8.8.8.8:53|169.254.169.254:53\", pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "Total hits"
    }
   ]
  },
  {
   "title": "Connection cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(coredns_forward_conn_cache_misses_total{to!~\"8.8.4.4:53|8.8.8.8:53|169.254.169.254:53\", pod=~\"$Pod\"}[$Rate])",
     "legendFormat": "Misses {{ pod }}"
    },
    {
     "expr": "sum(rate(coredns_forward_conn_cache_misses_total{to!~\"8.8.4.4:53|8.8.8.8:53|169.254.169.254:53\", pod=~\"$Pod\"}[$Rate]))",
     "legendFormat": "Total misses"
    }
   ]
  },
  { "title": ". zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\".\"}[$Rate])) by (server, rcode) > 0",
     "legendFormat": "{{ server }} / {{ rcode }}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\".\"}[$Rate])) by (le, server))",
     "legendFormat": "99% / {{ server }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\".\"}[$Rate])) by (le, server))",
     "legendFormat": "90% / {{ server }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\".\"}[$Rate])) by (server))",
     "legendFormat": "50% / {{ server }}"
    }
   ]
  },
  { "title": "cluster.local. zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\"cluster.local.\"}[$Rate])) by (server, rcode) > 0",
     "legendFormat": "{{ server }} / {{ rcode }}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\"cluster.local.\"}[$Rate])) by (le, server))",
     "legendFormat": "99% / {{ server }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\"cluster.local.\"}[$Rate])) by (le, server))",
     "legendFormat": "90% / {{ server }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"$PrometheusJob\",pod=~\"$Pod\", zone=\"cluster.local.\"}[$Rate])) by (server))",
     "legendFormat": "50% / {{ server }}"
    }
   ]
  }
 ]
}