apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-dns-debug
  name: kube-dns-debug
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
    reason: debug
  sessionAffinity: None
  type: ClusterIP
