apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-local-dns
  name: node-local-dns-metrics
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 9253
    protocol: TCP
    targetPort: 9253
  selector:
    k8s-app: node-local-dns
  type: ClusterIP
